#! /bin/bash

export APP_ID_DEMO='2b005ffe259546c9997d41ce33a21607'
export APP_SECRET_DEMO='f30cdb396d474afdaac806f52f4dedca'
export USER_DEMO='79999999999'
export USER_PWD_DEMO='1234'
export API_HOST=testapi.copernicusgold.com
export AUTH_HOST=testauth.copernicusgold.com

#
# Generating a value for Basic Authorization header
# $1 - APP_ID
# $2 - APP_SECRET
#
function buildBasic() {

   if [ -z $1 ]; then
	echo "APP_ID not specified"
	exit 1
   fi
   if [ -z $2 ]; then
        echo "APP_SECRET not specified"
        exit 1
   fi

   unamestr=`uname`

   unset BASIC

   if [[ "$unamestr" == 'Linux' ]]; then
      BASIC=`echo -n "$1:$2" | base64 -w 0`
   else
      BASIC=`echo "$1:$2\c" | base64`
   fi
}
export -f buildBasic

#
# This function obtains a test access token using the demo credentials
#
function getTestToken() {

   # Step 1. Generating the BASIC authentication header ( base64(app_id:app_secret) )
   APP_ID="$APP_ID_DEMO"
   APP_SECRET="$APP_SECRET_DEMO"

   buildBasic $APP_ID $APP_SECRET

   unset TOKEN
   rs=`curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' -H "Authorization: Basic $BASIC" -d "grant_type=password&username=$USER_DEMO&password=$USER_PWD_DEMO&scope=full" https://$AUTH_HOST/auth/oauth/token`

   TOKEN=$(echo $rs | jq .access_token | trim)
   echo "Obtained a token: $TOKEN"
}

export -f getTestToken

# Removes both quotes
function trim() {
    cat <<< `cat | sed -e 's/^"//' -e 's/"$//' -e 's/^\n//g'`
}

export -f trim

#
# Switching to a sample corporate entity
#
function switchToCorporate() {

    if [ -z $TOKEN ]; then
        echo "A token not found"
        exit 1
    fi

    # First of all, obtaining the whole list of available clients
    rs=`curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$API_HOST/api/v1/customers`

    # We have a demo corporate entity with the name 'The good company'
    ID=$(echo $rs | jq '.[] | select(.name == "The good company") | .id')

    # Setting the current customer as the company The good company'
    rs=`curl -s -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$API_HOST/api/v1/customers/$ID/current`
}

export -f switchToCorporate

#
# Creation of a sample application
#
function newApplication() {

    if [ -z $TOKEN ]; then
        echo "A token not found"
        exit 1
    fi

   MODEL='{}'
   rs=`curl -s -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" https://$API_HOST/api/v1/applications -d $MODEL`
   echo "Created App:"
   echo $rs | jq

   APP_ID=$(echo $rs | jq .app_id | trim)
   APP_SECRET=$(echo $rs | jq .app_secret | trim)

   # Now trying to authenticate in the Application
   buildBasic $APP_ID $APP_SECRET

   rs=`curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' -H "Authorization: Basic $BASIC" -d "grant_type=password&username=$USER_DEMO&password=$USER_PWD&scope=full" https://$AUTH_HOST/auth/oauth/token`

   TOKEN=$(echo $rs | jq .access_token | trim)
   
   switchToCorporate
}

export -f newApplication

#
# Removing an application
#
function removeApplication() {

   if [ -z $1 ]; then
    echo "APP_ID not specified"
    exit 1
   fi

   # Removing the application
   rs=`curl -s -X DELETE -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN" https://$API_HOST/api/v1/applications/$1`
   echo "Removing: $1"  
}

export -f removeApplication
